### ISSUE TITLE
 ERROR LOADING PLUGIN

### ISSUE THREAD

**Issue by mikes-techzone** [chris1705/homebridge-lightify#1]
# 

[2016-09-29 12:11:52] ERROR LOADING PLUGIN homebridge-lightify:
[2016-09-29 12:11:52] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:65:22)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:128:14)
    at Array.forEach (native)
[2016-09-29 12:11:52] ====================

**Comment by chris1705** [comment]
Which version of node are you using?

**Comment by mikes-techzone** [comment]
Hi,
I´m using v4.0.0 on Raspberry Pi

**Comment by mikes-techzone** [comment]
Okay I see,
your update on needs 

I update to Node 6.6 now it loads on startup, but how can i bind it in my config ?

**Comment by chris1705** [comment]
Sorry, I have added the newer version of nodejs to package.json. I also added an example configuration to the readme.md. Hope this helps :-)

Please let me know if it works.

**Comment by mikes-techzone** [comment]
Now it all works only the last  "," is to delete in config file
Thank you for your great work

**Comment by chris1705** [comment]
Oh, I'm sorry for this typo! 

Regards
