### ISSUE TITLE
Could not install 

### ISSUE THREAD

**Issue by Bettarg** [chris1705/homebridge-lightify#12]
Hello, wenn i try to Install die Plugin I get an Error. 

pi@raspberrypi:~ $ sudo npm install -g homebridge-lightify
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/homespun/node-lightify.git /root/.npm/_cacache/tmp/git-clone-33d4346c
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-33d4346c': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-29T19_30_32_029Z-debug.log

Any suggestions ?
Thanks a lot

**Comment by oleg77s** [comment]
1. install npm ver 4: sudo npm install -g npm@4
2. install plugin
3. return latest npm: sudo npm install -g npm@latest

**Comment by xxavarlon87** [comment]
Thats doesn't work for me. Installation works, but get an error when starting the hombridge service

Jun  8 20:33:18 raspberrypi systemd[1]: Started Node.js HomeKit Server.
Jun  8 20:33:19 raspberrypi homebridge[2450]: /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/ed25519-hap/node_modules/bindings/bindings.js:88
Jun  8 20:33:19 raspberrypi homebridge[2450]:         throw e
Jun  8 20:33:19 raspberrypi homebridge[2450]:         ^
Jun  8 20:33:19 raspberrypi homebridge[2450]: Error: The module '/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/ed25519-hap/build/Release/ed25519.node'
Jun  8 20:33:19 raspberrypi homebridge[2450]: was compiled against a different Node.js version using
Jun  8 20:33:19 raspberrypi homebridge[2450]: NODE_MODULE_VERSION 46. This version of Node.js requires
Jun  8 20:33:19 raspberrypi homebridge[2450]: NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
Jun  8 20:33:19 raspberrypi homebridge[2450]: the module (for instance, using `npm rebuild` or `npm install`).
Jun  8 20:33:19 raspberrypi homebridge[2450]:     at Object.Module._extensions..node (internal/modules/cjs/loader.js:731:18)
Jun  8 20:33:19 raspberrypi homebridge[2450]:     at Module.load (internal/modules/cjs/loader.js:612:32)
Jun  8 20:33:19 raspberrypi homebridge[2450]:     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
Jun  8 20:33:19 raspberrypi homebridge[2450]:     at Function.Module._load (internal/modules/cjs/loader.js:543:3)
Jun  8 20:33:19 raspberrypi homebridge[2450]:     at Module.require (internal/modules/cjs/loader.js:650:17)
Jun  8 20:33:19 raspberrypi homebridge[2450]:     at require (internal/modules/cjs/helpers.js:20:18)
Jun  8 20:33:19 raspberrypi homebridge[2450]:     at bindings (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/ed25519-hap/node_modules/bindings/bindings.js:81:44)
Jun  8 20:33:19 raspberrypi homebridge[2450]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/ed25519-hap/index.js:1:99)
Jun  8 20:33:19 raspberrypi homebridge[2450]:     at Module._compile (internal/modules/cjs/loader.js:702:30)
Jun  8 20:33:19 raspberrypi homebridge[2450]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)

I think it would be better to use Node 6.4.0 for plugin installation?

**Comment by xxavarlon87** [comment]
Sorry my fault. The Problem was Homebridge, which was compiled with Node V4. 
Forget it.
